name: document-management-system
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "${RABBIT_PORT}:5672"
      - "${RABBIT_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  documentdb:
    image: mongo:8
    container_name: documentdb
    restart: always
    ports:
      - "${DOCUMENT_DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCUMENT_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCUMENT_DB_ROOT_PASSWORD}
      DOCUMENT_DB_USER: ${DOCUMENT_DB_USER}
      DOCUMENT_DB_PASSWORD: ${DOCUMENT_DB_PASSWORD}
      DOCUMENT_DB_NAME: ${DOCUMENT_DB_NAME}
    volumes:
      - mongo_data:/data/db
      - ./scripts/init-document-db.sh:/docker-entrypoint-initdb.d/init-mongo.sh

volumes:
  rabbitmq_data:
  mongo_data:
    driver: local
